terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Second provider configuration targeting the archive Region. The default
# (unaliased) "aws" provider is generated by the root terragrunt.hcl and
# stays pointed at the source bucket's Region (set via AWS_DEFAULT_REGION).
provider "aws" {
  alias  = "destination"
  region = var.destination_region
}

# ---------------------------------------------------------------------------
# Destination bucket -- lives in the archive Region and only ever receives
# replicated copies. Nothing ever writes to or deletes from it directly.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "replica" {
  provider      = aws.destination
  bucket        = var.destination_bucket_name
  force_destroy = false

  tags = merge(var.tags, {
    Name = var.destination_bucket_name
  })
}

resource "aws_s3_bucket_public_access_block" "replica" {
  provider = aws.destination
  bucket   = aws_s3_bucket.replica.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_ownership_controls" "replica" {
  provider = aws.destination
  bucket   = aws_s3_bucket.replica.id

  rule {
    object_ownership = "BucketOwnerEnforced"
  }
}

# Required by S3 Replication -- both the source and destination buckets must
# be versioned.
resource "aws_s3_bucket_versioning" "replica" {
  provider = aws.destination
  bucket   = aws_s3_bucket.replica.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "replica" {
  provider = aws.destination
  bucket   = aws_s3_bucket.replica.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# ---------------------------------------------------------------------------
# IAM role S3 assumes on the source side to perform the replication.
# ---------------------------------------------------------------------------
data "aws_iam_policy_document" "replication_assume_role" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "replication" {
  name               = var.replication_role_name
  assume_role_policy = data.aws_iam_policy_document.replication_assume_role.json
  tags               = var.tags
}

data "aws_iam_policy_document" "replication" {
  statement {
    sid    = "SourceBucketPermissions"
    effect = "Allow"

    actions = [
      "s3:GetReplicationConfiguration",
      "s3:ListBucket",
    ]

    resources = [var.source_bucket_arn]
  }

  statement {
    sid    = "SourceObjectPermissions"
    effect = "Allow"

    actions = [
      "s3:GetObjectVersionForReplication",
      "s3:GetObjectVersionAcl",
      "s3:GetObjectVersionTagging",
    ]

    resources = ["${var.source_bucket_arn}/*"]
  }

  # Deliberately omits s3:ReplicateDelete. Replication here is one-way only:
  # deleting (or version-expiring) an object in the source bucket must never
  # delete or modify its replica in the archive bucket. Pairing that with
  # delete_marker_replication = "Disabled" below is what makes the archive
  # copy survive an accidental or malicious delete of the primary object.
  statement {
    sid    = "DestinationObjectPermissions"
    effect = "Allow"

    actions = [
      "s3:ReplicateObject",
      "s3:ReplicateTags",
    ]

    resources = ["${aws_s3_bucket.replica.arn}/*"]
  }
}

resource "aws_iam_role_policy" "replication" {
  name   = "${var.replication_role_name}-policy"
  role   = aws_iam_role.replication.id
  policy = data.aws_iam_policy_document.replication.json
}

# ---------------------------------------------------------------------------
# Replication configuration on the source bucket. Only covers objects
# created/updated after this rule is applied -- see the module README for
# backfilling objects that already existed in the bucket.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket_replication_configuration" "this" {
  # The role needs its policy attached, and the destination bucket needs
  # versioning enabled, before S3 will accept the replication configuration.
  depends_on = [
    aws_iam_role_policy.replication,
    aws_s3_bucket_versioning.replica,
  ]

  bucket = var.source_bucket_name
  role   = aws_iam_role.replication.arn

  rule {
    id     = var.replication_rule_id
    status = "Enabled"

    filter {}

    delete_marker_replication {
      status = "Disabled"
    }

    destination {
      bucket        = aws_s3_bucket.replica.arn
      storage_class = "DEEP_ARCHIVE"
    }
  }
}
