#!/bin/bash
set -e

NGINX_CONF="/etc/nginx/conf.d/elasticbeanstalk/00_application.conf"
WP_DIR="/var/www/efs/wordpress"

echo "Configuring Nginx for WordPress on EFS..."

# Wait for Nginx config to be generated by EB
sleep 2

# Backup original if exists
if [ -f "$NGINX_CONF" ] && [ ! -f "$NGINX_CONF.bak" ]; then
    cp "$NGINX_CONF" "$NGINX_CONF.bak"
fi

# Modify document root to point to WordPress on EFS
if [ -f "$NGINX_CONF" ]; then
    sed -i "s|root /var/www/html;|root $WP_DIR;|g" "$NGINX_CONF"
    
    # Add WordPress-specific location blocks if not already present
    if ! grep -q "try_files.*index.php" "$NGINX_CONF"; then
        # Find the location / block and update it
        sed -i '/location \/ {/,/}/ {
            /try_files/c\        try_files $uri $uri/ /index.php?$args;
        }' "$NGINX_CONF"
    fi
    
    echo "Nginx configuration updated for WordPress"
    
    # Test nginx config
    nginx -t
    
    # Reload nginx
    systemctl reload nginx
else
    echo "WARNING: Nginx config not found at $NGINX_CONF"
fi
