#!/bin/bash
# ============================================================
# EC2 user-data bootstrap script
# Runs once when an instance first launches (entering ASG or warm pool).
# On warm-pool restart, EFS is re-mounted via systemd (mount-efs.service).
# ============================================================
set -euo pipefail

# Redirect all output to a log file and the console simultaneously.
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1

echo "==> user-data starting at $(date -u)"

# ── IMDSv2 metadata ───────────────────────────────────────────────────────────────

TOKEN=$(curl -sX PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
REGION=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  "http://169.254.169.254/latest/meta-data/placement/region")
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" \
  "http://169.254.169.254/latest/meta-data/instance-id")

echo "==> Region: $REGION | Instance: $INSTANCE_ID"

# ── SSM helper ───────────────────────────────────────────────────────────────────

ssm_get() {
  aws ssm get-parameter \
    --region "$REGION" \
    --name "$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text
}

echo "==> Reading SSM parameters"
EFS_ID=$(ssm_get "/lodge104/efs/id")
DB_HOST=$(ssm_get "/lodge104/db/host")
DB_NAME=$(ssm_get "/lodge104/db/name")
DB_USER=$(ssm_get "/lodge104/db/username")
DB_PASS=$(ssm_get "/lodge104/db/password")
VALKEY_HOST=$(ssm_get "/lodge104/cache/host")
DOMAIN=$(ssm_get "/lodge104/app/domain")

# ── Persist EFS ID for systemd mount service (survives warm-pool stop/start) ─────

mkdir -p /etc/lodge104
echo "$EFS_ID" > /etc/lodge104/efs-id
chmod 600 /etc/lodge104/efs-id

# ── Mount EFS ──────────────────────────────────────────────────────────────────────

echo "==> Mounting EFS: $EFS_ID"
mkdir -p /var/www/html

if ! mountpoint -q /var/www/html; then
  mount -t efs -o tls,iam "${EFS_ID}":/ /var/www/html
fi

# Persist mount across reboots via fstab.
FSTAB_ENTRY="${EFS_ID}:/ /var/www/html efs _netdev,tls,iam 0 0"
if ! grep -qF "$EFS_ID" /etc/fstab; then
  echo "$FSTAB_ENTRY" >> /etc/fstab
fi

if ! mountpoint -q /var/www/html; then
  echo "ERROR: EFS mount failed — aborting" >&2
  exit 1
fi
echo "==> EFS mounted"

# ── First-time WordPress installation (atomic via EFS mkdir lock) ─────────────────

INSTALLED_FLAG=/var/www/html/wp-settings.php
LOCK_DIR=/var/www/html/.wp-installing

if [ ! -f "$INSTALLED_FLAG" ]; then
  if mkdir "$LOCK_DIR" 2>/dev/null; then
    echo "==> Installing WordPress core on EFS (first instance)"
    # Clean up lock if we exit unexpectedly.
    trap 'rm -rf "$LOCK_DIR"' EXIT ERR

    wp core download \
      --path=/var/www/html \
      --allow-root \
      --version=latest

    rm -rf "$LOCK_DIR"
    trap - EXIT ERR
    echo "==> WordPress core installed"
  else
    echo "==> Another instance is installing WordPress — waiting (max 5 min)..."
    for i in $(seq 1 60); do
      [ -f "$INSTALLED_FLAG" ] && break
      sleep 5
    done
    if [ ! -f "$INSTALLED_FLAG" ]; then
      echo "ERROR: Timed out waiting for WordPress installation" >&2
      exit 1
    fi
  fi
fi

# ── Write wp-config.php (refreshed on every boot to pick up SSM changes) ─────────

echo "==> Writing wp-config.php"

# Fetch WordPress security salts from the official API.
# This call only happens if the salts section is missing.
SALT_FILE=/var/www/html/.wp-salts
if [ ! -f "$SALT_FILE" ]; then
  echo "==> Fetching WordPress security salts"
  curl -sL "https://api.wordpress.org/secret-key/1.1/salt/" > "$SALT_FILE"
  chmod 600 "$SALT_FILE"
fi
SALTS=$(cat "$SALT_FILE")

cat > /var/www/html/wp-config.php << WPCONFIG
<?php
/**
 * WordPress configuration — managed by EC2 user-data.
 * Values are sourced from AWS SSM Parameter Store at boot time.
 * Do not edit this file manually; changes will be overwritten on restart.
 */

// ── Database ──────────────────────────────────────────────────────────────────────
define( 'DB_NAME',     '${DB_NAME}' );
define( 'DB_USER',     '${DB_USER}' );
define( 'DB_PASSWORD', '${DB_PASS}' );
define( 'DB_HOST',     '${DB_HOST}' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  'utf8mb4_unicode_ci' );

// ── Authentication keys and salts ─────────────────────────────────────────────────
${SALTS}

// ── Table prefix ─────────────────────────────────────────────────────────────────
\$table_prefix = 'wp_';

// ── Site URLs ─────────────────────────────────────────────────────────────────────
define( 'WP_HOME',    'https://${DOMAIN}' );
define( 'WP_SITEURL', 'https://${DOMAIN}' );

// ── HTTPS detection behind CloudFront / ALB ───────────────────────────────────────
// ALB sets X-Forwarded-Proto; this tells WordPress the connection is secure.
if ( isset( \$_SERVER['HTTP_X_FORWARDED_PROTO'] ) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
    \$_SERVER['HTTPS'] = 'on';
}

// ── Valkey / Redis object cache ───────────────────────────────────────────────────
define( 'WP_REDIS_HOST',     '${VALKEY_HOST}' );
define( 'WP_REDIS_PORT',     6379 );
define( 'WP_REDIS_DATABASE', 0 );
define( 'WP_REDIS_TIMEOUT',  1 );

// ── Performance ───────────────────────────────────────────────────────────────────
define( 'WP_MEMORY_LIMIT',     '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '512M' );
define( 'AUTOSAVE_INTERVAL',   300 );
define( 'WP_POST_REVISIONS',   5 );

// ── Security ──────────────────────────────────────────────────────────────────────
define( 'FORCE_SSL_ADMIN',      true );
define( 'DISALLOW_FILE_EDIT',   true );  // Disable theme/plugin editor in WP admin
define( 'DISALLOW_FILE_MODS',   false ); // Allow plugin/theme installs; set true to lock down

// ── Debugging (disable in production) ────────────────────────────────────────────
define( 'WP_DEBUG',         false );
define( 'WP_DEBUG_LOG',     false );
define( 'WP_DEBUG_DISPLAY', false );

// ── Bootstrap ─────────────────────────────────────────────────────────────────────
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
WPCONFIG

chmod 640 /var/www/html/wp-config.php

# ── Redis Object Cache plugin ─────────────────────────────────────────────────────

echo "==> Configuring Redis Object Cache plugin"
if ! wp plugin is-installed redis-cache --path=/var/www/html --allow-root 2>/dev/null; then
  wp plugin install redis-cache \
    --activate \
    --path=/var/www/html \
    --allow-root
fi

if ! wp plugin is-active redis-cache --path=/var/www/html --allow-root 2>/dev/null; then
  wp plugin activate redis-cache --path=/var/www/html --allow-root
fi

wp redis enable --path=/var/www/html --allow-root || true

# ── Permissions ───────────────────────────────────────────────────────────────────

echo "==> Setting file ownership"
chown apache:apache /var/www/html/wp-config.php
# Preserve existing EFS permissions; only fix top-level ownership if needed.
chown apache:apache /var/www/html

# ── CloudWatch agent ──────────────────────────────────────────────────────────────

echo "==> Starting CloudWatch agent"
systemctl enable amazon-cloudwatch-agent
systemctl start amazon-cloudwatch-agent || true

# ── Apache ────────────────────────────────────────────────────────────────────────

echo "==> Starting Apache"
systemctl enable httpd
systemctl start httpd

echo "==> Bootstrap complete at $(date -u)"
